spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/postgres
    username: ufc_user
    password: ufc_pass
  jpa:
    hibernate:
      ddl-auto: update   # creates tables automatically (dev only!)
    show-sql: true

